name: bitchannel
description: >
  A mix between an event-oriented package and a communication infrastructure 
  package based on channels and bits of information.
version: 2.0.0
repository: https://github.com/wattshout/flutter-packages/tree/main/bitchannel
issue_tracker: https://github.com/wattshout/flutter-packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22bitchannel%20package%22
homepage: https://wattshout.com

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.3"

flutter:

dependencies:
  flutter:
    sdk: flutter
  uuid_v4: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - event
  - communication
  - infrastructure
